version: 2

models:
  - name: stg_crm__contacts
    description: Cleaned CRM contact records with normalized email and phone
    columns:
      - name: crm_contact_id
        description: Primary key from CRM system
        tests: [unique, not_null]
      - name: email
        description: Lowercased, trimmed email (may be empty string)
      - name: phone_clean
        description: Phone with non-numeric chars stripped
      - name: source_system
        description: Always 'crm'

  - name: stg_crm__companies
    description: Cleaned CRM company records
    columns:
      - name: crm_company_id
        tests: [unique, not_null]

  - name: stg_billing__accounts
    description: Cleaned billing accounts with parsed first/last names from account_name
    columns:
      - name: billing_account_id
        tests: [unique, not_null]
      - name: first_name
        description: Parsed from account_name (handles "Last, First" format)
      - name: last_name
        description: Parsed from account_name
      - name: mrr_dollars
        description: Monthly recurring revenue in dollars

  - name: stg_billing__invoices
    description: Cleaned billing invoice records
    columns:
      - name: invoice_id
        tests: [unique, not_null]
      - name: billing_account_id
        tests: [not_null]

  - name: stg_support__users
    description: Cleaned support users with parsed names from display_name
    columns:
      - name: support_user_id
        tests: [unique, not_null]
      - name: email
        description: Nullable  - 25% of support users are phone-only
      - name: phone_clean
        description: Nullable  - 15% of support users are email-only

  - name: stg_support__tickets
    description: Cleaned support ticket records with resolution time
    columns:
      - name: ticket_id
        tests: [unique, not_null]
      - name: resolution_hours
        description: Hours from creation to resolution (null if unresolved)

  - name: stg_app__signups
    description: Cleaned product app signups
    columns:
      - name: app_user_id
        tests: [unique, not_null]
      - name: first_name
        description: Nullable  - 20% of users skipped name during signup
      - name: last_name
        description: Nullable  - 20% of users skipped name during signup

  - name: stg_app__events
    description: Cleaned product usage events
    columns:
      - name: event_id
        tests: [unique, not_null]

  - name: stg_partners__leads
    description: Cleaned partner-submitted leads (sparsest source)
    columns:
      - name: partner_lead_id
        tests: [unique, not_null]
      - name: email
        description: Nullable  - partner leads frequently missing contact info

  - name: stg_partners__referrals
    description: Cleaned partner referral records
    columns:
      - name: referral_id
        tests: [unique, not_null]
